name: Format code

on:
  push:

jobs:
  format:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Format code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Reformat code
